/*
 * Copyright (c) 2026 suretool contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.sure.tool.db;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

/**
 * sure-db 覆盖率补强测试（HSQLDB 内存库）：Entity 工具方法、各门面工厂、
 * SimpleDataSource 边界分支、SqlRunner 异常与参数分支。
 */
public class DbCoverageTest {

	private static final String URL = "jdbc:hsqldb:mem:dbcover;shutdown=false";

	private SimpleDataSource ds;

	@Before
	public void setUp() throws Exception {
		this.ds = new SimpleDataSource(URL, "sa", "");
		try (Connection conn = ds.getConnection()) {
			conn.createStatement().execute("DROP TABLE IF EXISTS t_cover");
			conn.createStatement().execute("""
					CREATE TABLE t_cover (
					    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					    name VARCHAR(50),
					    age INT,
					    score DOUBLE,
					    tag VARCHAR(20)
					)
					""");
		}
	}

	@After
	public void tearDown() {
		ds.close();
		DbUtil.setDefaultDataSource(null);
	}

	// ================= Entity =================

	@Test
	public void entityCreateFromMap() {
		Map<String, Object> map = new HashMap<>();
		map.put("name", "Map");
		map.put("age", 1);
		Entity e = Entity.create(map);
		assertEquals("Map", e.getStr("name"));
		assertEquals(Integer.valueOf(1), e.getInt("age"));
		// null map → 空实体
		Entity empty = Entity.create((Map<String, Object>) null);
		assertNotNull(empty);
		assertTrue(empty.isEmpty());
	}

	@Test
	public void entitySetTableNameChained() {
		Entity e = Entity.create().setTableName("t_cover");
		assertEquals("t_cover", e.getTableName());
	}

	@Test
	public void entitySetIgnoreNull() {
		Entity e = Entity.create();
		e.setIgnoreNull("a", "value");
		e.setIgnoreNull("b", null);
		assertEquals("value", e.getStr("a"));
		assertFalse(e.containsKey("b"));
	}

	@Test
	public void entityTypedGetters() {
		Entity e = Entity.create()
				.set("amount", new BigDecimal("12.34"))
				.set("born", new Date(System.currentTimeMillis()))
				.set("raw", new byte[] { 1, 2, 3 });
		assertEquals(new BigDecimal("12.34"), e.getBigDecimal("amount"));
		assertNotNull(e.getDate("born"));
		assertArrayEquals(new byte[] { 1, 2, 3 }, e.getBytes("raw"));
		// null 安全
		assertNull(e.getBigDecimal("none"));
		assertNull(e.getDate("none"));
		assertNull(e.getBytes("none"));
		// getDate 类型不匹配返回 null
		assertNull(e.getDate("amount"));
	}

	@Test
	public void entityCloneEqualsHashCode() {
		Entity a = Entity.create("t_cover").set("name", "x").set("age", 1);
		Entity copy = a.clone();
		assertEquals(a, copy);
		assertEquals(a.hashCode(), copy.hashCode());
		// 自反
		assertTrue(a.equals(a));
		// 非 Entity
		assertFalse(a.equals("string"));
		// 字段不同
		assertFalse(a.equals(Entity.create("t_cover").set("name", "y")));
		// 表名不同但字段相同也不等价（equals 比较 tableName）
		assertFalse(a.equals(Entity.create("other").set("name", "x").set("age", 1)));
	}

	// ================= Db / DbUtil 工厂 =================

	@Test
	public void dbUseWithConnectionParams() {
		Db db = Db.use(null, URL, "sa", "");
		assertNotNull(db);
		db.execute("INSERT INTO t_cover (name, age, score) VALUES ('F', 1, 1.0)");
		assertEquals(1L, db.queryCount("SELECT COUNT(*) FROM t_cover"));
	}

	@Test
	public void dbTxAlias() {
		Db db = Db.use(ds);
		db.tx(runner -> runner.insert(Entity.create("t_cover").set("name", "TX").set("age", 1).set("score", 1.0d)));
		assertEquals(1L, db.queryCount("SELECT COUNT(*) FROM t_cover"));
	}

	@Test
	public void dbUtilFactories() {
		DbUtil.setDefaultDataSource(ds);
		Db byDefault = DbUtil.use();
		assertNotNull(byDefault);
		Db byDs = DbUtil.use(ds);
		assertNotNull(byDs);
		Db byParams = DbUtil.use(null, URL, "sa", "");
		assertNotNull(byParams);
		SqlRunner runner = DbUtil.newSqlRunner(ds);
		assertNotNull(runner);
	}

	// ================= SimpleDataSource 边界 =================

	@Test
	public void simpleDataSourceConstructors() throws Exception {
		// 4 参（带 driver，无 maxSize）
		SimpleDataSource d1 = new SimpleDataSource(null, URL, "sa", "");
		assertNotNull(d1.getConnection().getMetaData());
		d1.close();
		// maxSize < 1
		assertThrows(IllegalArgumentException.class,
				() -> new SimpleDataSource(URL, "sa", "", 0));
	}

	@Test
	public void simpleDataSourceGetConnectionWithCredentials() throws Exception {
		try (Connection c = ds.getConnection("sa", "")) {
			assertTrue(c.isValid(3));
		}
	}

	@Test
	public void simpleDataSourceDoubleClose() {
		SimpleDataSource d = new SimpleDataSource(URL, "sa", "");
		d.close();
		d.close(); // 二次关闭直接返回，不报错
	}

	@Test
	public void simpleDataSourceMissingDriverRejected() {
		SimpleDataSource broken = new SimpleDataSource("no.such.DriverClass", URL, "sa", "");
		assertThrows(java.sql.SQLException.class, broken::getConnection);
		broken.close();
	}

	@Test
	public void simpleDataSourceReturnToPoolAfterClose() throws Exception {
		SimpleDataSource d = new SimpleDataSource(URL, "sa", "", 2);
		Connection held = d.getConnection();
		d.close(); // 关闭池
		held.close(); // 归还已关闭池 → 走 closed 分支
	}

	@Test
	public void wrappedConnectionPropagatesErrors() throws Exception {
		try (Connection c = ds.getConnection()) {
			// 包装连接上执行错误 SQL → 代理 InvocationTargetException 解包抛出
			assertThrows(java.sql.SQLException.class,
					() -> c.createStatement().executeQuery("SELECT * FROM no_such_table_xyz"));
		}
	}

	@Test
	public void dataSourceOptionalMethods() throws Exception {
		assertNull(ds.getLogWriter());
		ds.setLogWriter(null);
		ds.setLoginTimeout(5);
		assertEquals(0, ds.getLoginTimeout());
		assertNotNull(ds.getParentLogger());
		// unwrap 自展开
		assertSame(ds, ds.unwrap(SimpleDataSource.class));
		assertThrows(java.sql.SQLException.class, () -> ds.unwrap(String.class));
		assertTrue(ds.isWrapperFor(SimpleDataSource.class));
		assertFalse(ds.isWrapperFor(String.class));
	}

	// ================= SqlRunner 异常/参数分支 =================

	@Test
	public void queryBadSqlWraps() {
		Db db = Db.use(ds);
		assertThrows(DbRuntimeException.class, () -> db.query("SELECT * FROM nope_nope"));
	}

	@Test
	public void queryNumberEmptyAndBad() {
		Db db = Db.use(ds);
		// 无结果 → null
		assertNull(db.queryNumber("SELECT age FROM t_cover WHERE name = 'none'"));
		// 坏 SQL
		assertThrows(DbRuntimeException.class, () -> db.queryNumber("SELECT bad"));
	}

	@Test
	public void executeBadSqlWraps() {
		Db db = Db.use(ds);
		assertThrows(DbRuntimeException.class, () -> db.execute("INSERT INTO nope (x) VALUES (1)"));
	}

	@Test
	public void insertBadWraps() {
		Db db = Db.use(ds);
		assertThrows(DbRuntimeException.class, () -> db.insert(Entity.create("nope_nope").set("x", 1)));
	}

	@Test
	public void insertReturnKeyOnNonAutoTable() {
		Db db = Db.use(ds);
		// 普通表插入（无自增）也应返回；此处 t_cover 有自增主键
		Object key = db.insertReturnKey(Entity.create("t_cover").set("name", "K").set("age", 1).set("score", 1.0d));
		assertNotNull(key);
		// 坏插入走 catch
		assertThrows(DbRuntimeException.class, () -> db.insertReturnKey(Entity.create("bad_bad").set("x", 1)));
	}

	@Test
	public void updateAndDelBadWraps() {
		Db db = Db.use(ds);
		db.insert(Entity.create("t_cover").set("name", "U").set("age", 1).set("score", 1.0d));
		// 坏表
		assertThrows(DbRuntimeException.class,
				() -> db.update(Entity.create("bad_t").set("age", 2), Entity.create().set("name", "U")));
		assertThrows(DbRuntimeException.class,
				() -> db.del(Entity.create("bad_t"), Entity.create().set("name", "U")));
	}

	@Test
	public void pageNormalizesPageNoAndSize() {
		Db db = Db.use(ds);
		for (int i = 0; i < 5; i++) {
			db.insert(Entity.create("t_cover").set("name", "P" + i).set("age", i).set("score", i * 1.0d));
		}
		// pageNo<1 归一为 1
		PageResult p1 = db.page("SELECT * FROM t_cover ORDER BY id", null, 0, 2);
		assertEquals(1, p1.getPageNo());
		assertEquals(2, p1.getList().size());
		// pageSize<1 归一为 10
		PageResult p2 = db.page("SELECT * FROM t_cover ORDER BY id", null, 1, 0);
		assertEquals(10, p2.getPageSize());
	}

	@Test
	public void dbRuntimeExceptionOf() {
		Db db = Db.use(ds);
		try {
			db.query("SELECT * FROM missing_table_xyz");
		} catch (DbRuntimeException e) {
			assertTrue(e.getMessage().startsWith("数据库操作失败"));
			assertNotNull(e.getCause());
		}
	}

	@Test
	public void transactionReThrowsDbRuntimeException() {
		Db db = Db.use(ds);
		// 回调内坏 SQL 抛 DbRuntimeException，事务原样重抛
		assertThrows(DbRuntimeException.class, () -> db.transaction(runner -> {
			runner.execute("INSERT INTO t_cover (name, age, score) VALUES ('T', 1, 1.0)");
			runner.query("SELECT * FROM missing_xyz");
		}));
	}

	@Test
	public void closedDataSourceBorrowWraps() {
		SimpleDataSource closed = new SimpleDataSource(URL, "sa", "");
		closed.close();
		Db db = Db.use(closed);
		assertThrows(DbRuntimeException.class, () -> db.queryCount("SELECT 1 FROM (VALUES(1))"));
	}

	@Test
	public void bindNullParamsExplicitly() {
		SqlRunner runner = new SqlRunner(ds);
		// 显式传 null 数组 → bindParams 提前 return
		List<Entity> list = runner.query("SELECT 1 AS v FROM (VALUES(1))", (Object[]) null);
		assertEquals(1, list.size());
		assertEquals(1, list.get(0).getInt("v").intValue());
	}

	@Test
	public void whereWithMultipleConditions() {
		Db db = Db.use(ds);
		db.insert(Entity.create("t_cover").set("name", "M").set("age", 30).set("score", 1.0d).set("tag", "x"));
		// 多字段 where → 覆盖 AND 拼接
		int n = db.update(
				Entity.create("t_cover").set("score", 2.0d),
				Entity.create().set("name", "M").set("age", 30));
		assertEquals(1, n);
		int d = db.del(Entity.create("t_cover"), Entity.create().set("name", "M").set("age", 30));
		assertEquals(1, d);
	}

	@Test
	public void pageResultGetters() {
		PageResult pr = PageResult.of(2, 5, 12L, List.of());
		assertEquals(2, pr.getPageNo());
		assertEquals(5, pr.getPageSize());
		assertEquals(12L, pr.getTotal());
		assertEquals(3, pr.getPageCount());
	}

	@Test
	public void insertReturnKeyWithoutAutoColumn() throws Exception {
		// 普通表（无自增主键）：getGeneratedKeys 无行 → 返回 null
		try (Connection conn = ds.getConnection()) {
			conn.createStatement().execute("DROP TABLE IF EXISTS t_plain");
			conn.createStatement().execute("CREATE TABLE t_plain (id INT, name VARCHAR(20))");
		}
		Db db = Db.use(ds);
		Object key = db.insertReturnKey(Entity.create("t_plain").set("id", 1).set("name", "np"));
		assertNull(key);
	}

	@Test
	public void transactionWithClosedDataSource() {
		SimpleDataSource closed = new SimpleDataSource(URL, "sa", "");
		closed.close();
		Db db = Db.use(closed);
		// dataSource.getConnection() 抛 SQLException → 事务外层包装
		assertThrows(DbRuntimeException.class, () -> db.transaction(runner -> { }));
	}

	@Test
	public void borrowWaitInterrupted() throws Exception {
		SimpleDataSource tiny = new SimpleDataSource(URL, "sa", "", 1);
		Connection held = tiny.getConnection();
		Thread waiter = new Thread(() -> {
			try {
				tiny.getConnection();
			} catch (SQLException expected) {
				// 中断后抛 SQLException
			}
		});
		waiter.start();
		Thread.sleep(500); // 进入 wait
		waiter.interrupt();
		waiter.join();
		held.close();
		tiny.close();
	}

	@Test
	public void borrowDetectsInvalidIdleConnection() throws Exception {
		String memUrl = "jdbc:hsqldb:mem:invalididle;shutdown=false";
		SimpleDataSource d = new SimpleDataSource(memUrl, "sa", "");
		Connection c = d.getConnection();
		c.close(); // raw 回到空闲队列（此时有效）
		// 用独立原生连接关闭该内存库，使空闲连接失效
		try (Connection raw = java.sql.DriverManager.getConnection(memUrl, "sa", "")) {
			raw.createStatement().execute("SHUTDOWN");
		}
		// 再次借出：轮询到失效空闲连接 → 剔除（isValid 失败）后重建
		Connection rebuilt = d.getConnection();
		assertTrue(rebuilt.isValid(3));
		rebuilt.close();
		d.close();
	}

	@Test
	public void returnInvalidConnectionAfterDbDown() throws Exception {
		String memUrl = "jdbc:hsqldb:mem:invalidret;shutdown=false";
		SimpleDataSource d = new SimpleDataSource(memUrl, "sa", "");
		Connection c = d.getConnection(); // 借用，raw 活跃
		// 关闭 DB，使该连接失效
		try (Connection raw = java.sql.DriverManager.getConnection(memUrl, "sa", "")) {
			raw.createStatement().execute("SHUTDOWN");
		}
		c.close(); // 归还：isValid 失败 → 按失效真实关闭
		d.close();
	}

	@Test
	public void createWithKnownDriver() throws Exception {
		// 传入真实驱动类名：Class.forName 正常完成
		SimpleDataSource d = new SimpleDataSource("org.hsqldb.jdbc.JDBCDriver", URL, "sa", "");
		try (Connection c = d.getConnection()) {
			assertTrue(c.isValid(3));
		}
		d.close();
	}

	@Test
	public void returnAbortedConnection() throws Exception {
		String memUrl = "jdbc:hsqldb:mem:abortret;shutdown=false";
		SimpleDataSource d = new SimpleDataSource(memUrl, "sa", "");
		Connection c = d.getConnection();
		java.util.concurrent.Executor exec = java.util.concurrent.Executors.newSingleThreadExecutor();
		c.abort(exec); // 中止底层真实连接
		c.close(); // 归还：isValid 为 false → 走失效关闭分支
		((java.util.concurrent.ExecutorService) exec).shutdown();
		d.close();
	}

	@Test
	@SuppressWarnings("unchecked")
	public void borrowDetectsClosedIdleConnection() throws Exception {
		String memUrl = "jdbc:hsqldb:mem:closedidle;shutdown=false";
		SimpleDataSource d = new SimpleDataSource(memUrl, "sa", "");
		Connection c = d.getConnection();
		c.close(); // raw 进入空闲队列（此时有效）
		// 反射取出空闲队列中的真实连接并强行关闭，但它仍留在队列
		java.lang.reflect.Field f = SimpleDataSource.class.getDeclaredField("idle");
		f.setAccessible(true);
		java.util.Deque<Connection> idle = (java.util.Deque<Connection>) f.get(d);
		Connection raw = idle.peekLast();
		raw.close();
		// 再次借出：轮询到已关闭空闲连接 → isValid false → 剔除后重建
		Connection rebuilt = d.getConnection();
		assertTrue(rebuilt.isValid(3));
		rebuilt.close();
		d.close();
	}

	// ================= helpers =================

	/**
	 * 构造可在指定方法上抛 SQLException 的连接代理，其余方法委托真实连接。
	 *
	 * @param real               真实连接
	 * @param throwRollback      rollback() 是否抛错
	 * @param throwRestoreCommit setAutoCommit(true) 是否抛错
	 * @return 代理连接
	 */
	private static Connection throwingConn(Connection real, boolean throwRollback, boolean throwRestoreCommit) {
		return (Connection) java.lang.reflect.Proxy.newProxyInstance(
				DbCoverageTest.class.getClassLoader(),
				new Class<?>[] { Connection.class },
				(proxy, method, args) -> {
					String name = method.getName();
					if (throwRollback && "rollback".equals(name)) {
						throw new java.sql.SQLException("强制 rollback 失败");
					}
					if (throwRestoreCommit && "setAutoCommit".equals(name) && Boolean.TRUE.equals(args[0])) {
						throw new java.sql.SQLException("强制恢复 autoCommit 失败");
					}
					return method.invoke(real, args);
				});
	}

	/**
	 * 仅返回指定连接的极简数据源（其余方法为占位）。
	 *
	 * @param conn 固定返回的连接
	 * @return 数据源
	 */
	private static DataSource fixedDs(Connection conn) {
		return new DataSource() {
			public Connection getConnection() {
				return conn;
			}

			public Connection getConnection(String username, String password) {
				return conn;
			}

			public java.io.PrintWriter getLogWriter() {
				return null;
			}

			public void setLogWriter(java.io.PrintWriter out) {
			}

			public void setLoginTimeout(int seconds) {
			}

			public int getLoginTimeout() {
				return 0;
			}

			public java.util.logging.Logger getParentLogger() {
				return java.util.logging.Logger.getGlobal();
			}

			public <T> T unwrap(Class<T> iface) {
				throw new UnsupportedOperationException();
			}

			public boolean isWrapperFor(Class<?> iface) {
				return false;
			}
		};
	}

	@Test
	public void transactionRollbackFailureAddsSuppressed() throws Exception {
		Connection real = ds.getConnection();
		Connection proxy = throwingConn(real, true, false);
		SqlRunner runner = new SqlRunner(fixedDs(proxy));
		// 回调抛错 → rollback 也抛错 → 命中 addSuppressed 分支
		assertThrows(DbRuntimeException.class,
				() -> runner.transaction(r -> {
					throw new RuntimeException("boom");
				}));
		real.close();
	}

	@Test
	public void transactionRestoreAutoCommitFailureIgnored() throws Exception {
		Connection real = ds.getConnection();
		Connection proxy = throwingConn(real, false, true);
		SqlRunner runner = new SqlRunner(fixedDs(proxy));
		// 事务正常提交，finally 恢复 autoCommit 抛错被吞
		runner.transaction(r -> r.execute("INSERT INTO t_cover (name, age, score) VALUES ('R', 1, 1.0)"));
		real.close();
	}

	private static void assertArrayEquals(byte[] expected, byte[] actual) {
		org.junit.Assert.assertArrayEquals(expected, actual);
	}
}
