/*
 * Copyright (c) 2026 suretool contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.sure.tool.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 * sure-db 集成测试（HSQLDB 内存库，test scope）。
 */
public class DbTest {

	private static final String URL = "jdbc:hsqldb:mem:suretest;shutdown=false";

	private SimpleDataSource dataSource;

	@Before
	public void setUp() throws Exception {
		this.dataSource = new SimpleDataSource(URL, "sa", "");
		try (Connection conn = dataSource.getConnection()) {
			conn.createStatement().execute("DROP TABLE IF EXISTS t_user");
			conn.createStatement().execute("""
					CREATE TABLE t_user (
					    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					    name VARCHAR(50),
					    age INT,
					    score DOUBLE
					)
					""");
		}
	}

	@After
	public void tearDown() {
		dataSource.close();
		DbUtil.setDefaultDataSource(null);
	}

	@Test
	public void 连接池自动探测与复用() throws Exception {
		// driver 为 null：DriverManager 自动探测 HSQLDB
		Connection first = dataSource.getConnection();
		Assert.assertTrue(first.isValid(3));
		first.close(); // 归还
		Connection second = dataSource.getConnection();
		Assert.assertTrue(second.isValid(3));
		second.close();
	}

	@Test
	public void 连接池上限等待超时() throws Exception {
		SimpleDataSource tiny = new SimpleDataSource(URL, "sa", "", 1);
		try {
			Connection held = tiny.getConnection();
			long start = System.currentTimeMillis();
			try {
				tiny.getConnection();
				Assert.fail("池满应超时抛 SQLException");
			} catch (SQLException expected) {
				Assert.assertTrue("应等待接近借用超时", System.currentTimeMillis() - start >= 9000);
			} finally {
				held.close();
			}
			// 归还后可再次借出
			Assert.assertTrue(tiny.getConnection().isValid(3));
		} finally {
			tiny.close();
		}
	}

	@Test
	public void 数据源关闭后拒绝借出() throws Exception {
		SimpleDataSource ds = new SimpleDataSource(URL, "sa", "");
		Connection conn = ds.getConnection();
		conn.close();
		ds.close();
		try {
			ds.getConnection();
			Assert.fail("关闭后应抛 SQLException");
		} catch (SQLException expected) {
			// 符合预期
		}
	}

	@Test
	public void entity链式与类型化取值() {
		Entity entity = Entity.create("t_user")
				.set("name", "Alice")
				.set("age", 30)
				.set("score", 95.5d)
				.set("active", "true");
		Assert.assertEquals("t_user", entity.getTableName());
		Assert.assertEquals("Alice", entity.getStr("name"));
		Assert.assertEquals(Integer.valueOf(30), entity.getInt("age"));
		Assert.assertEquals(Long.valueOf(30L), entity.getLong("age"));
		Assert.assertEquals(Double.valueOf(95.5d), entity.getDouble("score"));
		Assert.assertEquals(Boolean.TRUE, entity.getBool("active"));
		Assert.assertNull(entity.getInt("no_such"));
	}

	@Test
	public void insert生成主键并查询() {
		Db db = Db.use(dataSource);
		Object key = db.insertReturnKey(Entity.create("t_user").set("name", "Bob").set("age", 25).set("score", 88.0d));
		Assert.assertNotNull("IDENTITY 应生成主键", key);

		Entity row = db.queryOne("SELECT * FROM t_user WHERE id = ?", key);
		Assert.assertEquals("Bob", row.getStr("name"));
		Assert.assertEquals(25, (int) row.getInt("age"));

		// 带别名：列 label 生效
		Entity aliased = db.queryOne("SELECT name AS n FROM t_user WHERE id = ?", key);
		Assert.assertEquals("Bob", aliased.getStr("n"));
	}

	@Test
	public void queryNumber与queryCount() {
		Db db = Db.use(dataSource);
		db.insert(Entity.create("t_user").set("name", "A").set("age", 1).set("score", 10.0d));
		db.insert(Entity.create("t_user").set("name", "B").set("age", 2).set("score", 20.0d));

		long count = db.queryCount("SELECT COUNT(*) FROM t_user");
		Assert.assertEquals(2L, count);
		Number avg = db.queryNumber("SELECT AVG(age * 1.0) FROM t_user");
		Assert.assertEquals(1.5d, avg.doubleValue(), 0.0001);
	}

	@Test
	public void 参数绑定防注入与null参数() {
		Db db = Db.use(dataSource);
		db.insert(Entity.create("t_user").set("name", "Alice; DROP TABLE t_user").set("age", 18).set("score", 60.0d));

		// 注入载荷应作为普通值，而非改变 SQL
		List<Entity> rows = db.query("SELECT * FROM t_user WHERE name = ?", "Alice; DROP TABLE t_user");
		Assert.assertEquals(1, rows.size());
		// 表仍存在
		Assert.assertEquals(1L, db.queryCount("SELECT COUNT(*) FROM t_user"));

		// null 参数：WHERE name IS NULL 语义（此处无匹配）
		Assert.assertEquals(0, db.query("SELECT * FROM t_user WHERE name = ?", new Object[] {null}).size());
	}

	@Test
	public void update与del两种形态() {
		Db db = Db.use(dataSource);
		db.insert(Entity.create("t_user").set("name", "X").set("age", 10).set("score", 50.0d));
		db.insert(Entity.create("t_user").set("name", "Y").set("age", 20).set("score", 60.0d));

		// SQL 形态
		int updated = db.update("UPDATE t_user SET age = age + 1 WHERE name = ?", "X");
		Assert.assertEquals(1, updated);
		// Entity 形态
		int updated2 = db.update(
				Entity.create("t_user").set("age", 99),
				Entity.create().set("name", "Y"));
		Assert.assertEquals(1, updated2);
		Assert.assertEquals(99, (int) db.queryOne("SELECT age FROM t_user WHERE name = ?", "Y").getInt("age"));

		// SQL 删除
		Assert.assertEquals(1, db.del("DELETE FROM t_user WHERE name = ?", "X"));
		// Entity 删除
		Assert.assertEquals(1, db.del(Entity.create("t_user"), Entity.create().set("name", "Y")));
		Assert.assertEquals(0L, db.queryCount("SELECT COUNT(*) FROM t_user"));
	}

	@Test
	public void 事务成功提交() {
		Db db = Db.use(dataSource);
		db.transaction(runner -> {
			runner.insert(Entity.create("t_user").set("name", "TX1").set("age", 1).set("score", 1.0d));
			runner.insert(Entity.create("t_user").set("name", "TX2").set("age", 2).set("score", 2.0d));
		});
		Assert.assertEquals(2L, db.queryCount("SELECT COUNT(*) FROM t_user"));
	}

	@Test
	public void 事务异常自动回滚() {
		Db db = Db.use(dataSource);
		try {
			db.transaction(runner -> {
				runner.insert(Entity.create("t_user").set("name", "ROLLBACK").set("age", 1).set("score", 1.0d));
				throw new IllegalStateException("模拟业务失败");
			});
			Assert.fail("应抛 DbRuntimeException");
		} catch (DbRuntimeException expected) {
			// 符合预期
		}
		Assert.assertEquals("事务内写入应全部回滚", 0L, db.queryCount("SELECT COUNT(*) FROM t_user"));
	}

	@Test
	public void 分页查询() {
		Db db = Db.use(dataSource);
		for (int i = 1; i <= 25; i++) {
			db.insert(Entity.create("t_user").set("name", "U" + i).set("age", i).set("score", i * 1.0d));
		}
		PageResult page1 = db.page("SELECT * FROM t_user ORDER BY id", null, 1, 10);
		Assert.assertEquals(25L, page1.getTotal());
		Assert.assertEquals(3, page1.getPageCount());
		Assert.assertEquals(10, page1.getList().size());
		Assert.assertEquals("U1", page1.getList().get(0).getStr("name"));

		PageResult page3 = db.page("SELECT * FROM t_user ORDER BY id", null, 3, 10);
		Assert.assertEquals(5, page3.getList().size());
		Assert.assertEquals("U25", page3.getList().get(4).getStr("name"));

		PageResult empty = db.page("SELECT * FROM t_user WHERE age > ?", new Object[] {999}, 1, 10);
		Assert.assertEquals(0L, empty.getTotal());
		Assert.assertEquals(0, empty.getPageCount());
	}

	@Test
	public void DbUtil全局默认数据源() {
		DbUtil.setDefaultDataSource(dataSource);
		Db db = DbUtil.use();
		db.execute("""
				INSERT INTO t_user (name, age, score) VALUES ('DEF', 7, 7.0)
				""");
		Entity row = Db.use().queryOne("SELECT * FROM t_user WHERE name = ?", "DEF");
		Assert.assertEquals("DEF", row.getStr("name"));

		// 未设置默认数据源应抛清晰异常
		DbUtil.setDefaultDataSource(null);
		try {
			Db.use();
			Assert.fail("应抛 DbRuntimeException");
		} catch (DbRuntimeException expected) {
			Assert.assertTrue(expected.getMessage().contains("默认数据源"));
		}
	}

	@Test
	public void 虚拟线程并发访问() throws Exception {
		Db db = Db.use(dataSource);
		int threads = 8;
		CountDownLatch start = new CountDownLatch(1);
		CountDownLatch done = new CountDownLatch(threads);
		AtomicReference<Throwable> error = new AtomicReference<>();
		for (int i = 0; i < threads; i++) {
			int no = i;
			Thread.startVirtualThread(() -> {
				try {
					start.await();
					for (int j = 0; j < 20; j++) {
						db.insert(Entity.create("t_user").set("name", "VT" + no).set("age", no).set("score", no * 1.0d));
						db.queryCount("SELECT COUNT(*) FROM t_user");
					}
				} catch (Throwable e) {
					error.set(e);
				} finally {
					done.countDown();
				}
			});
		}
		start.countDown();
		done.await();
		Assert.assertNull("并发访问不应抛错: " + error.get(), error.get());
	}

	@Test
	public void 表名缺失抛清晰异常() {
		Db db = Db.use(dataSource);
		try {
			db.insert(Entity.create().set("name", "x"));
			Assert.fail("应抛 IllegalArgumentException");
		} catch (IllegalArgumentException expected) {
			Assert.assertTrue(expected.getMessage().contains("表名"));
		}
		try {
			db.update(Entity.create("t_user").set("age", 1), Entity.create());
			Assert.fail("空条件应抛 IllegalArgumentException");
		} catch (IllegalArgumentException expected) {
			// 符合预期
		}
	}
}
